-- Auto-generated by drizzle-kit, rewritten to be idempotent.
--
-- 0041_phase1_4_features already applied:
--   agent_project_manager_draft_status enum, agent_project_manager_drafts/applies,
--   task_dependencies, ai_reminders, agent_task_planner_drafts/applies changes,
--   ai_findings.source, calendar_connections.scope,
--   sticky_notes/tasks/document_chunks.embedding (vector),
--   sticky_notes.public_id, direct_conversations.public_id,
--   CREATE EXTENSION vector, and all related indexes.
--
-- This file handles the remaining schema drift that drizzle-kit detected,
-- using IF NOT EXISTS / exception handlers so re-running is harmless.

-- ── Enums (may already exist from 0035-0039 migrations) ──────────────────────
DO $$ BEGIN
  CREATE TYPE "public"."event_cover" AS ENUM('dusk', 'ember', 'meadow', 'blush', 'sand', 'tide');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "public"."event_topic" AS ENUM('tech', 'music', 'food', 'sport', 'art', 'business', 'education', 'community');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "public"."notification_position" AS ENUM('top-left', 'top-center', 'top-right', 'bottom-left', 'bottom-center', 'bottom-right');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "public"."profile_audience" AS ENUM('everyone', 'organization', 'shared');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "public"."verification_code_purpose" AS ENUM('email_verify', 'password_reset');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint

-- ── Tables ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "user_follow" (
  "follower_id" varchar(255) NOT NULL,
  "following_id" varchar(255) NOT NULL,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "user_follow_follower_id_following_id_pk" PRIMARY KEY("follower_id","following_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "verification_code" (
  "id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY
    (sequence name "verification_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
  "purpose" "verification_code_purpose" NOT NULL,
  "email" varchar(255) NOT NULL,
  "code_hash" varchar(64) NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "consumed_at" timestamp with time zone,
  "attempts" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_cohost" (
  "event_id" integer NOT NULL,
  "user_id" varchar(255) NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  CONSTRAINT "event_cohost_event_id_user_id_pk" PRIMARY KEY("event_id","user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_save" (
  "event_id" integer NOT NULL,
  "user_id" varchar(255) NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  CONSTRAINT "event_save_event_id_user_id_pk" PRIMARY KEY("event_id","user_id")
);
--> statement-breakpoint

-- ── Columns that may already exist from 0030-0039 migrations ─────────────────
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "notification_position" "notification_position" DEFAULT 'top-right' NOT NULL;
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "profile_audience" "profile_audience" DEFAULT 'organization' NOT NULL;
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "allow_followers" boolean DEFAULT true NOT NULL;
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "show_activity_feed" boolean DEFAULT true NOT NULL;
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "last_seen_at" timestamp with time zone;
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "calendar_feed_token" varchar(64);
--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "image" text;
--> statement-breakpoint
ALTER TABLE "event_comment" ADD COLUMN IF NOT EXISTS "parent_id" integer;
--> statement-breakpoint
ALTER TABLE "event" ADD COLUMN IF NOT EXISTS "ends_at" timestamp with time zone;
--> statement-breakpoint
ALTER TABLE "event" ADD COLUMN IF NOT EXISTS "venue" varchar(160);
--> statement-breakpoint
ALTER TABLE "event" ADD COLUMN IF NOT EXISTS "address" varchar(255);
--> statement-breakpoint
ALTER TABLE "event" ADD COLUMN IF NOT EXISTS "capacity" integer;
--> statement-breakpoint
ALTER TABLE "event" ADD COLUMN IF NOT EXISTS "topic" "event_topic";
--> statement-breakpoint
ALTER TABLE "event" ADD COLUMN IF NOT EXISTS "cover_theme" "event_cover";
--> statement-breakpoint
ALTER TABLE "event" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone;
--> statement-breakpoint

-- ── Foreign keys (wrapped to skip if already present) ─────────────────────────
DO $$ BEGIN
  ALTER TABLE "user_follow" ADD CONSTRAINT "user_follow_follower_id_user_id_fk"
    FOREIGN KEY ("follower_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "user_follow" ADD CONSTRAINT "user_follow_following_id_user_id_fk"
    FOREIGN KEY ("following_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "event_cohost" ADD CONSTRAINT "event_cohost_event_id_event_id_fk"
    FOREIGN KEY ("event_id") REFERENCES "public"."event"("id") ON DELETE cascade ON UPDATE no action NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "event_cohost" ADD CONSTRAINT "event_cohost_user_id_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "event_save" ADD CONSTRAINT "event_save_event_id_event_id_fk"
    FOREIGN KEY ("event_id") REFERENCES "public"."event"("id") ON DELETE cascade ON UPDATE no action NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "event_save" ADD CONSTRAINT "event_save_user_id_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS "user_follow_following_idx" ON "user_follow" USING btree ("following_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "verification_code_lookup_idx" ON "verification_code" USING btree ("email","purpose");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cohost_user_idx" ON "event_cohost" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "save_user_idx" ON "event_save" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "comment_parent_idx" ON "event_comment" USING btree ("parent_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_topic_idx" ON "event" USING btree ("topic");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_date_id_idx" ON "event" USING btree ("event_date","id");
--> statement-breakpoint

-- ── Unique constraints ────────────────────────────────────────────────────────
DO $$ BEGIN
  ALTER TABLE "user" ADD CONSTRAINT "user_calendar_feed_token_unique" UNIQUE ("calendar_feed_token");
EXCEPTION WHEN others THEN NULL;
END $$;
